{{ if .Values.web.istioVirtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/target: api-cname.{{ .Values.envName }}.flodplains.com
  name: "temporal-web-vs"
  namespace: "{{ $.Release.Namespace }}"
spec:
  gateways:
    - "{{ $.Release.Namespace }}-gateway-internet-facing"
  hosts:
    - "temporal.{{ .Values.envName }}.flodplains.com"
  http:
    - route:
        - destination:
            host: {{ include "temporal.componentname" (list . "web") }}
            port:
              number: 8080
{{ end }}
